// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Pet_Management.Migrations
{
    [DbContext(typeof(EntrySetContext))]
    [Migration("20191110050530_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pet_Management.Models.DPETTYPE", b =>
                {
                    b.Property<short>("d_type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("crt_dt")
                        .HasColumnType("datetime2");

                    b.Property<long>("crt_usr")
                        .HasColumnType("bigint");

                    b.Property<string>("d_type_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("m_type_id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("upd_dt")
                        .HasColumnType("datetime2");

                    b.Property<long>("upd_usr")
                        .HasColumnType("bigint");

                    b.HasKey("d_type_id");

                    b.ToTable("DPETTYPE");
                });

            modelBuilder.Entity("Pet_Management.Models.HEALTHCARE", b =>
                {
                    b.Property<long>("healthcare_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("crt_dt")
                        .HasColumnType("datetime2");

                    b.Property<long>("crt_usr")
                        .HasColumnType("bigint");

                    b.Property<long>("pet_id")
                        .HasColumnType("bigint");

                    b.Property<string>("place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("service_id")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("upd_dt")
                        .HasColumnType("datetime2");

                    b.Property<long>("upd_usr")
                        .HasColumnType("bigint");

                    b.HasKey("healthcare_id");

                    b.ToTable("HEALTHCARE");
                });

            modelBuilder.Entity("Pet_Management.Models.IMAGE", b =>
                {
                    b.Property<long>("image_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("crt_dt")
                        .HasColumnType("datetime2");

                    b.Property<long>("crt_usr")
                        .HasColumnType("bigint");

                    b.Property<string>("image_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("upd_dt")
                        .HasColumnType("datetime2");

                    b.Property<long>("upd_usr")
                        .HasColumnType("bigint");

                    b.HasKey("image_id");

                    b.ToTable("IMAGE");
                });

            modelBuilder.Entity("Pet_Management.Models.MCITY", b =>
                {
                    b.Property<int>("city_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("city_id");

                    b.ToTable("MCITY");
                });

            modelBuilder.Entity("Pet_Management.Models.MDISTRICT", b =>
                {
                    b.Property<int>("district_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("city_id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("district_id");

                    b.ToTable("MDISTRICT");
                });

            modelBuilder.Entity("Pet_Management.Models.MFURCOLOR", b =>
                {
                    b.Property<int>("color_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("avatar")
                        .HasColumnType("bigint");

                    b.Property<string>("color_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("crt_dt")
                        .HasColumnType("datetime2");

                    b.Property<long>("crt_usr")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("upd_dt")
                        .HasColumnType("datetime2");

                    b.Property<long>("upd_usr")
                        .HasColumnType("bigint");

                    b.HasKey("color_id");

                    b.ToTable("MFURCOLOR");
                });

            modelBuilder.Entity("Pet_Management.Models.MPETTYPE", b =>
                {
                    b.Property<short>("m_type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("crt_dt")
                        .HasColumnType("datetime2");

                    b.Property<long>("crt_usr")
                        .HasColumnType("bigint");

                    b.Property<string>("m_type_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("upd_dt")
                        .HasColumnType("datetime2");

                    b.Property<long>("upd_usr")
                        .HasColumnType("bigint");

                    b.HasKey("m_type_id");

                    b.ToTable("MPETTYPE");
                });

            modelBuilder.Entity("Pet_Management.Models.MSERVICE", b =>
                {
                    b.Property<short>("checkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("checkName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("crt_dt")
                        .HasColumnType("datetime2");

                    b.Property<long>("crt_usr")
                        .HasColumnType("bigint");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("upd_dt")
                        .HasColumnType("datetime2");

                    b.Property<long>("upd_usr")
                        .HasColumnType("bigint");

                    b.HasKey("checkID");

                    b.ToTable("MSERVICE");
                });

            modelBuilder.Entity("Pet_Management.Models.MWARD", b =>
                {
                    b.Property<int>("ward_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("district_id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ward_id");

                    b.ToTable("MWARD");
                });

            modelBuilder.Entity("Pet_Management.Models.PET", b =>
                {
                    b.Property<long>("petID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("birthday")
                        .HasColumnType("datetime2");

                    b.Property<long>("color")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("crt_dt")
                        .HasColumnType("datetime2");

                    b.Property<long>("crt_usr")
                        .HasColumnType("bigint");

                    b.Property<long>("father")
                        .HasColumnType("bigint");

                    b.Property<short>("gender")
                        .HasColumnType("smallint");

                    b.Property<long>("mother")
                        .HasColumnType("bigint");

                    b.Property<long>("owner")
                        .HasColumnType("bigint");

                    b.Property<string>("petName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.Property<DateTime>("upd_dt")
                        .HasColumnType("datetime2");

                    b.Property<long>("upd_usr")
                        .HasColumnType("bigint");

                    b.HasKey("petID");

                    b.ToTable("PET");
                });

            modelBuilder.Entity("Pet_Management.Models.PET_IMG", b =>
                {
                    b.Property<long>("pet_id")
                        .HasColumnType("bigint");

                    b.Property<long>("img_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("crt_dt")
                        .HasColumnType("datetime2");

                    b.Property<long>("crt_usr")
                        .HasColumnType("bigint");

                    b.Property<long>("service_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("upd_dt")
                        .HasColumnType("datetime2");

                    b.Property<long>("upd_usr")
                        .HasColumnType("bigint");

                    b.HasKey("pet_id", "img_id");

                    b.HasAlternateKey("img_id", "pet_id");

                    b.ToTable("PET_IMG");
                });

            modelBuilder.Entity("Pet_Management.Models.PURCHASE", b =>
                {
                    b.Property<long>("purchase_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("crt_dt")
                        .HasColumnType("datetime2");

                    b.Property<long>("crt_usr")
                        .HasColumnType("bigint");

                    b.Property<string>("note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("number")
                        .HasColumnType("smallint");

                    b.Property<long>("pet_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("seller")
                        .HasColumnType("bigint");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("upd_dt")
                        .HasColumnType("datetime2");

                    b.Property<long>("upd_usr")
                        .HasColumnType("bigint");

                    b.HasKey("purchase_id");

                    b.ToTable("PURCHASE");
                });

            modelBuilder.Entity("Pet_Management.Models.PURCHASE_IMG", b =>
                {
                    b.Property<long>("purchase_id")
                        .HasColumnType("bigint");

                    b.Property<long>("img_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("crt_dt")
                        .HasColumnType("datetime2");

                    b.Property<long>("crt_usr")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("upd_dt")
                        .HasColumnType("datetime2");

                    b.Property<long>("upd_usr")
                        .HasColumnType("bigint");

                    b.HasKey("purchase_id", "img_id");

                    b.HasAlternateKey("img_id", "purchase_id");

                    b.ToTable("PURCHASE_IMG");
                });

            modelBuilder.Entity("Pet_Management.Models.SCHEDULE", b =>
                {
                    b.Property<long>("schedule_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("crt_dt")
                        .HasColumnType("datetime2");

                    b.Property<long>("crt_usr")
                        .HasColumnType("bigint");

                    b.Property<long>("pet_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("schedule_time")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("upd_dt")
                        .HasColumnType("datetime2");

                    b.Property<long>("upd_usr")
                        .HasColumnType("bigint");

                    b.HasKey("schedule_id");

                    b.ToTable("SCHEDULE");
                });

            modelBuilder.Entity("Pet_Management.Models.USER", b =>
                {
                    b.Property<long>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("avatar")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("birthday")
                        .HasColumnType("datetime2");

                    b.Property<short>("classification")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("crt_dt")
                        .HasColumnType("datetime2");

                    b.Property<long>("crt_usr")
                        .HasColumnType("bigint");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("facebook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("gender")
                        .HasColumnType("smallint");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("role")
                        .HasColumnType("smallint");

                    b.Property<short>("status")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("upd_dt")
                        .HasColumnType("datetime2");

                    b.Property<long>("upd_usr")
                        .HasColumnType("bigint");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("user_id");

                    b.ToTable("USER");
                });

            modelBuilder.Entity("Pet_Management.Models.VIDEO", b =>
                {
                    b.Property<long>("vid_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("crt_dt")
                        .HasColumnType("datetime2");

                    b.Property<long>("crt_usr")
                        .HasColumnType("bigint");

                    b.Property<string>("path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("upd_dt")
                        .HasColumnType("datetime2");

                    b.Property<long>("upd_usr")
                        .HasColumnType("bigint");

                    b.Property<string>("vid_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("vid_id");

                    b.ToTable("VIDEO");
                });
#pragma warning restore 612, 618
        }
    }
}
